/// <reference types="@angular/localize" />

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { registerLicense } from '@syncfusion/ej2-base';
registerLicense('Mgo+DSMBaFt+QHJqVk1mQ1NCaV1CX2BZdll3RGlbfU4QCV5EYF5SRHNdRV9jSH9RdUFmWn0=;Mgo+DSMBPh8sVXJ1S0R+X1pCaV1EQmFJfFBmTWlYflRydkUmHVdTRHRcQlhhTnxTd0RhWntYeHY=;ORg4AjUWIQA/Gnt2VFhiQlJPcEBAW3xLflF1VWtTfl96dldWACFaRnZdQV1mS3lRdkRiW3xaeHdX;MjIyMjk5MkAzMjMxMmUzMDJlMzBCck41Q3JtTnIveWhwUGc5aUIwRVVVZ1BtWUxuODdwcFhOVndJUHg4NEpFPQ==;MjIyMjk5M0AzMjMxMmUzMDJlMzBsRWxVeDJScGw2V2RHMmNBMlh2em5FMWFJVmUvS3FKU01QazBKTUtXN1NnPQ==;NRAiBiAaIQQuGjN/V0d+Xk9HfVldX2VWfFN0RnNRdV9xfldEcDwsT3RfQF5jTHxUdEViWH1ddXFVRA==;MjIyMjk5NUAzMjMxMmUzMDJlMzBJZk5GMFdSQTJxS1k2U3VVSTNwd2VwY2RCWDdHd3dwbzQ5OU9HdVcyMDRBPQ==;MjIyMjk5NkAzMjMxMmUzMDJlMzBMYXZESG5LZGl2WFA4NGpKamFyeDNjWm03cXJ2dGtyaFl0R0Qzc25uU1Z3PQ==;Mgo+DSMBMAY9C3t2VFhiQlJPcEBAW3xLflF1VWtTfl96dldWACFaRnZdQV1mS3lRdkRiW3xYcnZW;MjIyMjk5OEAzMjMxMmUzMDJlMzBSSmlTM0cvSTE5SGl4QVdQRi9JbWhLSXNOMTBvKzVLRDUrM1E2SE50MlBJPQ==;MjIyMjk5OUAzMjMxMmUzMDJlMzBvQ09XZDZNTEZwc2d5UzVFZVkxZGZHVmNMNFVWQnRYN3FTVWd4YmwzQ2lJPQ==;MjIyMzAwMEAzMjMxMmUzMDJlMzBJZk5GMFdSQTJxS1k2U3VVSTNwd2VwY2RCWDdHd3dwbzQ5OU9HdVcyMDRBPQ==');
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
